home:
    path:     /
    defaults: 
        _controller: 'HomeController'
        _action: 'indexAction'

blog:
    path:     /blog
    defaults: 
        _controller: 'HomeController'
        _action: 'indexAction'

blog_post:
    path:     /blog/{id}
    defaults: 
        _controller: 'HomeController'
        _action: 'detailAction'